stages:
  - lint
  - test
  - build
  - deploy

lint_job:
  stage: lint
  image: node:20-alpine
  script:
    - npm install
    - npm run lint

test_job:
  stage: test
  image: node:20-alpine
  script:
    - npm install
    - npm run test

build_job:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

clean_ci_for_amplify:
  stage: build
  image: node:20-alpine
  script:
    - npm ci

pages:
  stage: build
  needs:
    - job: build_job
  script:
    - rm -rf public
    - cp -r dist public
    - rm -rf dist
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public

deploy_job:
  stage: deploy
  image: python:3.12-alpine
  dependencies:
    - build_job
  needs:
    - job: build_job
  script:
    - pip install awscli
    - aws s3 sync dist/ s3://need4deed --delete
  when: manual
  only:
    - main
