stages:
  - test
  - build

build_job:
  stage: build
  image: node:20-alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist

clean_ci_for_amplify:
  stage: test
  image: node:20-alpine
  script:
    - yarn install --frozen-lockfile
