stages:
  - pre-commit
  - test
  - build

pre_commit_job:
  stage: pre-commit
  image: node:20-alpine
  script:
    - apk add git
    - yarn install
    - yarn pre-commit

test_job:
  stage: test
  image: node:20-alpine
  script:
    - yarn install
    - yarn test

validate_job:
  stage: test
  image: node:20-alpine
  script:
    - apk add jq
    - ./validate_data.sh ./public/data/opportunities.json Status Name Type District Schedule "Languages needed"
    - ./validate_data.sh ./public/data/accompanying.json Name Address "Appointment Type" Date "District (Appointment)" Languages Status

build_job:
  stage: build
  image: node:20-alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist

clean_ci_for_amplify:
  stage: test
  image: node:20-alpine
  script:
    - yarn install --frozen-lockfile
