import { ListsOfOptionsType } from "../../config/types";

const fallbackLists: ListsOfOptionsType = {
  locations: [
    "Mitte",
    "Moabit",
    "Wedding",
    "Friedrichshain",
    "Kreuzberg",
    "Pankow",
    "Prenzlauer Berg",
    "Weißensee",
    "Charlottenburg",
    "Wilmersdorf",
    "Spandau",
    "Steglitz",
    "Zehlendorf",
    "Tempelhof",
    "Schöneberg",
    "Neukölln",
    "Treptow",
    "Köpenick",
    "Marzahn",
    "Hellersdorf",
    "Lichtenberg",
    "Reinickendorf",
    "Tegel",
    "Rudow",
    "Remotely",
  ],
  activities: [
    "Daycare",
    "Sports",
    "Teaching German",
    "Translation at Accommodation Centers",
    "Accompanying to doctors' or government appointments",
    "Arts & Crafts",
    "Gardening",
    "One-day Volunteering (e.g. Festivals, Cleanups)",
    "Playing board games",
    "Reading books for children",
    "Activities for women",
    "Activities for men",
    "Assist with homework",
    "Sorting clothing",
    "Organizing excursions",
  ],
  skills: [
    "Woodworking",
    "Drawing",
    "Painting",
    "Sewing",
    "Knitting",
    "Repairs",
    "Cooking",
    "Teaching",
    "Programming",
    "Public speaking",
    "Gardening",
    "Landscaping",
    "Carpentry",
    "Decorating",
    "Bike repairs",
    "Photography",
    "Videography",
    "Makeup",
    "Copywriting",
    "Yoga",
    "Fitness",
    "Football",
    "Basketball",
    "Dance",
    "Chess",
    "Management",
    "SMM",
    "Mediation",
    "Event planning",
    "Coaching",
    "Guitar",
    "Piano",
    "Singing",
  ],
  languages: [
    "German",
    "English",
    "Arabic",
    "Farsi",
    "Turkish",
    "Russian",
    "Ukrainian",
    "French",
    "Kurdish",
    "Armenian",
    "Belarusian",
    "Chechen",
    "Chinese",
    "Czech",
    "Dari",
    "Dutch",
    "Georgian",
    "Greek",
    "Hebrew",
    "Hindi",
    "Italian",
    "Pashto",
    "Polish",
    "Punjabi",
    "Romanes",
    "Serbian",
    "Somali",
    "Spanish",
    "Swedish",
    "Urdu",
    "Vietnamese",
    "Other",
  ],
  leads: [
    "Volunteering platform",
    "Social media",
    "A newsletter",
    "Web search",
    "Friends",
    "Volunteer fair",
    "Flyer/Poster",
  ],
  racNames: [
    "GU Soorstr.",
    "GU Columbiadamm",
    "AE/GU Invalidenstr.",
    "GU Grünauer Str.",
    "GU Murtzaner Ring",
    "AE Hangar 1-3",
    "das Integrationsbüro T-K",
    "GU Kiefholzstr. 36",
    "GU Storkowerstr. 118",
  ],
};

export default fallbackLists;
