name: Mirror to GitLab
on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run pre-commit
        run: yarn pre-commit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  mirror:
    needs: test # Ensure tests pass before mirroring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Add GitLab remote
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/https://gitlab.com/need4deed/website.git"
      - name: Push to GitLab (Temporary Branch)
        run: |
          GITLAB_BRANCH="mirror-temp-${{ github.run_id }}" # create a unique branch name
          git checkout -b "$GITLAB_BRANCH"
          git push gitlab "$GITLAB_BRANCH"
      - name: Create Merge Request
        run: |
          GITLAB_BRANCH="mirror-temp-${{ github.run_id }}"
          curl --request POST \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data "{ \"source_branch\": \"$GITLAB_BRANCH\", \"target_branch\": \"main\", \"title\": \"Mirror from GitHub\" }" \
            "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_REPO_PATH_ENCODED }}/merge_requests" #GITLAB_REPO_PATH_ENCODED needs to be url encoded.
      - name: Delete temporary branch (optional)
        run: |
          GITLAB_BRANCH="mirror-temp-${{ github.run_id }}"
          curl --request DELETE \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" \
            "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_REPO_PATH_ENCODED }}/repository/branches/$GITLAB_BRANCH"
        continue-on-error: true # if deletion fails, continue.
env:
  GITLAB_REPO_PATH_ENCODED: ${{ github.repository_owner }}%2F${{ github.event.repository.name }}
