name: Mirror to GitLab
on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run pre-commit
        run: yarn pre-commit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  mirror:
    needs: test # Ensure tests pass before mirroring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Add GitLab remote
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/${{ secrets.GITLAB_REPO_PATH }}.git"
      - name: Push to GitLab
        run: |
          git push -f gitlab main
