import { ListsOfOptionsType } from "../../config/types";

const fallbackLists: Partial<ListsOfOptionsType> = {
  activities: [
    "Kinderbetreuung",
    "Sport",
    "Sprachcafé",
    "Sprachmittlung in Unterkünften",
    "Ausfüllhilfe",
    "Basteln",
    "Gartenarbeit",
    "Eintägiges Engagement (z. B. Feier, Aufräumaktionen)",
    "Brettspiele spielen",
    "Bücher vorlesen für Kinder",
    "Aktivitäten für Frauen*",
    "Aktivitäten für Männer*",
    "Nachhilfe",
    "Kleiderkammer",
    "Ausflüge organisieren",
    "Sonstiges",
  ],
  activitiesAccompanying: [
    "Arzttermine",
    "Termine bei Behörden*",
    "Wohnungsbesichtigungen",
    "Termine in Schulen und Kitas",
    "Wegbegleitung",
  ],
  skills: [
    "Holzverarbeitung",
    "Zeichnen",
    "Malen",
    "Nähen",
    "Stricken",
    "Reparaturen",
    "Kochen",
    "Lehren",
    "Programmieren",
    "Öffentliches Sprechen",
    "Gartenarbeit",
    "Landschaftsgestaltung",
    "Tischlerei",
    "Dekorieren",
    "Fahrradreparaturen",
    "Fotografie",
    "Videografie",
    "Make-up",
    "Kreatives Schreiben",
    "Yoga",
    "Fitness",
    "Fußball",
    "Basketball",
    "Tanzen",
    "Schach",
    "Management",
    "Social-Media-Management (SMM)",
    "Mediation",
    "Veranstaltungsplanung",
    "Coaching",
    "Gitarre",
    "Klavier",
    "Singen",
  ],
  languages: [
    "Deutsch",
    "Englisch",
    "Arabisch",
    "Farsi",
    "Türkisch",
    "Russisch",
    "Ukrainisch",
    "Französisch",
    "Kurdisch",
    "Armenisch",
    "Weißrussisch",
    "Tschetschenisch",
    "Chinesisch",
    "Tschechisch",
    "Dari",
    "Niederländisch",
    "Georgisch",
    "Griechisch",
    "Hebräisch",
    "Hindi",
    "Italienisch",
    "Paschtu",
    "Polnisch",
    "Punjabi",
    "Romanes",
    "Serbisch",
    "Somali",
    "Spanisch",
    "Schwedisch",
    "Urdu",
    "Vietnamesisch",
    "Andere",
  ],
};

export default fallbackLists;
